Pin vendored `tree-sitter-tcl` to known-good rev
Upstream commit 802deaf [1] of the vendored `tree-sitter-tcl` dependency
switched to language version 15 [2], which is incompatible with the
version that tree-sitter-language-pack expects.

This causes the TCL integration to fail. Here’s a small self-contained
reproducer:

```py
from tree_sitter import Language, Parser
import tree_sitter_language_pack.bindings.tcl as binding
capsule = binding.language()
language = Language(capsule)
Parser(language)                # <== causes a ValueError
```

The reproducer results in the following error:

> ValueError: Incompatible Language version 15. Must be between 13 and 14

The following unit test fails with the same error:

```py
pytest -k 'test_get_parser[tcl]' --import-mode=append tests
```

Pin `tree-sitter-tcl` to the last known-good upstream commit.

[1]: https://github.com/tree-sitter-grammars/tree-sitter-tcl/commit/802deaff8e127ee20f1d5f9e58ab959003f24b92

[2]: https://github.com/tree-sitter-grammars/tree-sitter-tcl/blob/802deaff8e127ee20f1d5f9e58ab959003f24b92/src/parser.c#L9